### ISSUE TITLE
No app functionality enabled

### ISSUE THREAD

**Issue by hayasisuny** [itzmeanjan/intent#1]
Thank you for creating great features.
Unfortunately, there is one problem.

When you install several apps created with this function on your mobile phone,
There is a problem that the function does not work and Google Play update does not work.

I found this symptom in the phone dialing feature.

Calling a Number : #

**Comment by itzmeanjan** [comment]
Thanks @hayasisuny , I'll take a look into it.

**Comment by itzmeanjan** [comment]
Hello @hayasisuny this issue has been resolved in new version 1.2.0 on pub.dev

Thanks to @agniswarm 

![Screenshot_2020-04-26 intent Flutter Package](https://user-images.githubusercontent.com/45074836/80313667-f71a4a80-8809-11ea-9ce1-96af69ec4c0d.png)
