### ISSUE TITLE
how to send parameters ?

### ISSUE THREAD

**Issue by Ali-Azmoud** [itzmeanjan/intent#11]
Hi
How can I send parameters like this? ( this is android native )
```
Intent intent = new Intent("com.bpmellat.merchant");
intent.putExtra("PaymentData","{'param1':'value'}"); 
startActivityForResult(intent); 
```

thanks in advance

**Comment by itzmeanjan** [comment]
hey @Ali-Azmoud  did you try checking usage examples provided [here](https://github.com/itzmeanjan/intent#how-to-use-it-) ?
