### ISSUE TITLE
Set Some Configration for app

### ISSUE THREAD

**Issue by khaledpro2012** [itzmeanjan/intent#13]
how set **package**
how set **ClassName**

https://developer.android.com/reference/android/content/Intent.html#setComponent(android.content.ComponentName)

**Comment by itzmeanjan** [comment]
Sorry didn't understand query :thinking:

**Comment by itzmeanjan** [comment]
Hello @khaledpro2012 , you query has been resolved in v1.3.0 of `intent`. 

Thanks to PR by @togiberlin .
