### ISSUE TITLE
adding contact with paramters like name,title etc..

### ISSUE THREAD

**Issue by kw2019ltd** [itzmeanjan/intent#15]
hi 
its possible to add contact with extra data and how its being done any exmaple

**Comment by itzmeanjan** [comment]
Hello @kw2019ltd , you can check [this](https://github.com/itzmeanjan/intent/#add-a-contact-to-your-contact-database-) usage example for putting new contact into contact database on Android.

You can add more extras *( using putExtra() method )*.

**Comment by kw2019ltd** [comment]
not working only tel is populated.

pls add complete example how to add contact with extra param like firstname last name etc

below not wokring
```
inal intent = intentImpl.Intent()
          ..setAction('com.android.contacts.action.SHOW_OR_CREATE_CONTACT')
          ..setData(
            Uri(
              scheme: 'tel',
              path: qrCodeDetails['number'],
            ),
          )
          ..putExtra('firstname', 'watted')
          ..putExtra('title', 'mr');
```

**Comment by kw2019ltd** [comment]
hi any update
