### ISSUE TITLE
how to open contact detail page

### ISSUE THREAD

**Issue by urvashikharecha** [itzmeanjan/intent#16]
I want following code via this plugging can someone help how can i do??

```
Intent intent = new Intent(Intent.ACTION_VIEW);
Uri uri = Uri.withAppendedPath(ContactsContract.Contacts.CONTENT_URI,
String.valueOf(contactID));
intent.setData(uri);
context.startActivity(intent);
```

**Comment by itzmeanjan** [comment]
Hello @urvashikharecha , there's a little problem.

The way you're using this plugin, isn't how it's supposed to be used. I'd rather suggest you to go through README.md, which has lots of example usage cases.

Check this [usage](https://github.com/itzmeanjan/intent#share-text-media-). Then try to find out proper Intent Action that needs to be set for doing what you're interested in getting done.

**Comment by urvashikharecha** [comment]
> Hello @urvashikharecha , there's a little problem.
> 
> The way you're using this plugin, isn't how it's supposed to be used. I'd rather suggest you to go through README.md, which has lots of example usage cases.
> 
> Check this [usage](https://github.com/itzmeanjan/intent#share-text-media-). Then try to find out proper Intent Action that needs to be set for doing what you're interested in getting done.



> I want following code via this plugging can someone help how can i do??
> 
> ```
> Intent intent = new Intent(Intent.ACTION_VIEW);
> Uri uri = Uri.withAppendedPath(ContactsContract.Contacts.CONTENT_URI,
> String.valueOf(contactID));
> intent.setData(uri);
> context.startActivity(intent);
> ```

this is in android i m no using this plugin i want to use but i dont know how this android code can be implemented via your plugin.

**Comment by itzmeanjan** [comment]
Try using some thing like this

```dart
Intent()
        ..setAction(Action.ACTION_VIEW)
        ..setData(Uri(...))
        ..startActivity().catchError((e) => print(e));
```
