### ISSUE TITLE
latest version error BuildConfig.java:12: error: annotations are not supported in -source 1.3   @Deprecated

### ISSUE THREAD

**Issue by kw2019ltd** [itzmeanjan/intent#19]
C:\Users\kotai\AndroidStudioProjects\barcode_app\build\intent\generated\source\buildConfig\debug\io\github\itzmeanjan\intent\BuildConfig.java:12: error: annotations are not supported in -source 1.3
  @Deprecated
   ^
  (use -source 5 or higher to enable annotations)
1 error
3 warnings

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':intent:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

**Comment by itzmeanjan** [comment]
Hey @kw2019ltd , thanks for reporting !!!

I'm digging in :)

**Comment by itzmeanjan** [comment]
This issue has been resolved. Soon to be pushed on pub.dev.

@kw2019ltd

**Comment by itzmeanjan** [comment]
Fixed version of `intent` v1.3.3 available for use [here](https://pub.dev/packages/intent).

Thanks :)
