### ISSUE TITLE
Add setClassName method

### ISSUE THREAD

**Issue by carmas123** [itzmeanjan/intent#2]
Hi, please can you add setClassName method to your library?
Regards,
Massimo

**Comment by itzmeanjan** [comment]
Hello @carmas123 , can you please be more specific, how would that benefit it ?

**Comment by neelayak** [comment]
hi this will be helpful sir as i recently made app autostart in the android device and for that, I need to take the user to the device-specific auto-start screen tried different way also https://stackoverflow.com/questions/60648026/how-to-call-intent-method-from-java-using-flutter
