### ISSUE TITLE
how can i make intent call without opening phone dialer any help

### ISSUE THREAD

**Issue by hssn-hassnain** [itzmeanjan/intent#23]
hi really appreciate the work you have done on the app can i ask how should i make call from my app, i don't want to use the phone dial-er, because i am creating a phone calling and receive app. Any help in it will be really helpfull for me thanks

**Comment by itzmeanjan** [comment]
Hello @hssn-hassnain , thanks for stopping by :)

Here's little example usage on [*how to use `intent` for dialing phone numbers on Android ?*](https://github.com/itzmeanjan/intent#dial-a-number-using-default-dial-activity-)

**Comment by hssn-hassnain** [comment]
what permission it requires here i tried it is giving permission error
Permission Denial: starting Intent { act=android.intent.action.CALL dat=tel:xxx cmp=com.android.server.telecom/.components.UserCallActivity } from ProcessRecord{552fc13 7467:io.github.itzmeanjan.intent_example/u0a151} (pid=7467, uid=10151) requires android.permission.CALL_PHONE, null)
