### ISSUE TITLE
How to get result of Action.ACTION_CALL?

### ISSUE THREAD

**Issue by fipooo** [itzmeanjan/intent#27]
how to get result in Flutter from android_intent.Intent()? I have code like below and how to get info when call will be disconnected?

```
android_intent.Intent()
                      ..setAction(android_action.Action.ACTION_CALL)
                      ..setData(Uri(scheme: "tel", path: 'phone number'))
                      ..startActivity();
```

**Comment by ghenry** [comment]
Are you looking to make a call or is your app registered for `tel` and you're trying to receive the number clicked?
