### ISSUE TITLE
Set As Wallpaper Android Intent

### ISSUE THREAD

**Issue by imran-nadeem** [itzmeanjan/intent#28]
Hi i want to set an image as wallpaper using the android native intent which opens these option when we select set as wallpaper on any image.
Please help me figure this out by providing code. I would be very thankful to you.
Thanks
https://user-images.githubusercontent.com/5235221/84620253-effde780-aef0-11ea-910a-cffa48cff142.jpg

**Comment by vjk10** [comment]
Same problem. Any update on this?
