### ISSUE TITLE
intent service to detect screen on off

### ISSUE THREAD

**Issue by georgeraveen** [itzmeanjan/intent#33]
can I use this to detect screen on off?
or else any other way?

**Comment by itzmeanjan** [comment]
Have you discovered any Action which can do so ?

**Comment by georgeraveen** [comment]
No, not yet. There is a flutter plugin [https://pub.dev/packages/screen_state](https://pub.dev/packages/screen_state).
but it doesn't work in the background.

**Comment by itzmeanjan** [comment]
Then I guess you can do it natively i.e. write some kotlin/ java code to do so, they have that kind of API.
