### ISSUE TITLE
How to share image to WhatsApp particular specified  number

### ISSUE THREAD

**Issue by Sreejithtechno** [itzmeanjan/intent#42]
How to share image to WhatsApp particular specified  number. it it possible???

**Comment by itzmeanjan** [comment]
Most probably yes. All you need to do is to figure what parameters need to be passed as `extra`, so that whatsapp can perform what you want to perform.

**Comment by Sreejithtechno** [comment]
RaisedButton(
                color: Colors.cyanAccent,
                elevation: 16,
                onPressed: () => android_intent.Intent()
                  ..setAction(android_action.Action.ACTION_VIEW)
                  ..setPackage("com.whatsapp")
                  ..setData(Uri.parse('whatsapp://send?phone=919562173404&text=hi'))
                  ..startActivity().catchError((e) => print(e)),
                  child: Text('share'),
              )
and

RaisedButton(
                color: Colors.cyanAccent,
                elevation: 16,
                onPressed: () => android_intent.Intent()
                  ..setAction(android_action.Action.ACTION_SENDTO)
                  ..setPackage("com.whatsapp")
                  ..setData(Uri.parse("smsto:" mobile_number))
                  ..startActivity().catchError((e) => print(e)),
                  child: Text('share'),
              )

this two function is working good perticular number sending is working. i want to pass the image also in this function .

**Comment by itzmeanjan** [comment]
> this two function is working good perticular number sending is working. i want to pass the image also in this function .

You need to pass image that you want to share by passing it as `extra`

**Comment by itzmeanjan** [comment]
You can take a look at [this](https://github.com/itzmeanjan/intent#share-text-media-)
