### ISSUE TITLE
Cannot display specific image in Gallery

### ISSUE THREAD

**Issue by BoHellgren** [itzmeanjan/intent#7]
Hi! Thanks for a great plugin. I am using

`android_intent.Intent()
              ..setAction(android_action.Action.ACTION_MAIN)
              ..addCategory(android_category.Category.CATEGORY_APP_GALLERY)
              ..startActivity().catchError((e) => print(e));`

to bring up the Gallery. This works, but what I really want to do is to start the Gallery app with the latest image being displayed. This is what the standard Camera app does, so it should be possible. I have tried some putExtra and addFlag but they seem to be ignored.

Any idea how to accomplish this?

**Comment by itzmeanjan** [comment]
Did you check [it](https://developer.android.com/reference/android/content/Intent.html#intent-structure), which holds actual intent info and options for android platform ? 

If not consider doing so, because **intent** 's imitates android intent api _( java based )_
