### ISSUE TITLE
android:authorities wrong

### ISSUE THREAD

**Issue by thesipguy** [itzmeanjan/intent#9]
Hi, the plugin hardcodes the plugin authority to io.github.itzmeanjan.intent.fileProvider and it causes a conflict when using 2 apps on the same phone that use the library, here is the error I got

 Failure [INSTALL_FAILED_CONFLICTING_PROVIDER: Package couldn't be installed in /data/app/com.blankedOut.projectone-RhGbhs4NKuaKfdXJ62UF5w==: Can't install because provider name io.github.itzmeanjan.intent.fileProvider (in package com.blankedOut.projectone) is already used by com.blankedOut.projecttwo]

You cannot have 2 apps with this library on the same phone, please fix the provider id

**Comment by agniswarm** [comment]
+1

**Comment by itzmeanjan** [comment]
Hello @thesipguy ,this issue has been resolved in published new version 1.2.0 on pub.dev.

Thanks to @agniswarm 

![Screenshot_2020-04-26 intent Flutter Package](https://user-images.githubusercontent.com/45074836/80313640-c63a1580-8809-11ea-99fe-cb01a0f0f8fa.png)
